version: '3'
services:
  docker:
    image: docker:20.10.17
    ports:
      - "2375:2375"
    volumes:
      - /var/lib/docker:/var/lib/docker
    environment:
      - DOCKER_VERSION=20.10.17
    command: --version